---
title: "reading data from the web"
output: github_document
---

```{r setup}
library(tidyverse)
library(rvest)
library(httr)
```

## scrape a table

I want the first table from [this page](http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm)

read in the html

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_table = read_html(url)
```

extract the table(s); focus on the first one

```{r}
table_marj = 
  drug_use_table %>%
  html_nodes(css = "table") %>%
  first() %>% 
  html_table() %>%
  slice(-1) %>% 
  as_tibble()

table_marj
```

## Star wars movie info

I want data from [here](https://www.imdb.com/list/ls070150896/)

```{r}
url = "https://www.imdb.com/list/ls070150896/"

swm_html = read_html(url)
```

Grab elements that I want

```{r}
title_vec = 
  swm_html %>%
  html_nodes(css = ".lister-item-header a") %>%
  html_text()
  

gross_rev_vec = 
  swm_html %>%
  html_nodes(".text-muted .ghost~ .text-muted+ span") %>%
  html_text()

runtime_vec = 
  swm_html %>%
  html_nodes(".runtime") %>%
  html_text()

swm_df = 
  tibble(
    title = title_vec,
    gross_rev = gross_rev_vec,
    runtime = runtime_vec
  )
```

## get some info about nyc water data

this is coming from API

```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>% 
  content("parsed")

nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") %>%
  content("text") %>%
  jsonlite::fromJSON() %>%
  as_tibble()
```

##BRFSS

same process, different data

```{r}
brfss_df = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) %>% 
  content("parsed")
```

## Some data is not so nice

let look at Pokemon

```{r}
pokemon_df = 
  GET("https://pokeapi.co/api/v2/pokemon/ditto") %>% 
  content
  
pokemon_df$name
pokemon_df$height
pokemon_df$abilities
```

